; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu]
platform = espressif8266
board         = nodemcuv2
framework = esp8266-rtos-sdk
monitor_speed = 115200 

upload_port   = COM9      ; <-- change to your port
monitor_port  = COM9      ; optional but handy

; Use custom single-image map compatible with your bootloader, larger irom
board_build.ldscript = ld/eagle.app.v6.custom.ld
; Make flash header/settings explicit for stability on clones
board_build.flash_mode = dout
board_build.f_flash    = 40000000
board_build.flash_size = 4MB

build_flags =
  -Os
  -flto
  -Wl,-Map,.pio/build/nodemcu/firmware.map
  -DMQTT_TLS_MODE=1   ; 0=OFF, 1=TLS no-verify (smaller), 2=verify CA
  -DMBEDTLS_SSL_MAX_CONTENT_LEN=768
  -DMINIMAL_WIFI_EVENTS
  ; -DENABLE_STACK_MON
  ; -DENABLE_LOG=1
  -Wl,--start-group
  -lmbedtls
  -Wl,--end-group