[Service]
User=mosq
Group=mosq
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p /var/log/mosquitto
ExecStartPre=/bin/touch /var/log/mosquitto/mosquitto.log
ExecStartPre=/bin/chown mosq:mosq /var/log/mosquitto /var/log/mosquitto/mosquitto.log
